import { useEffect, useRef, useState } from "react";

type Health = { status: string; service: string; updatedAt: string };
type Message = { role: "assistant" | "user"; text: string };
const routes = [{ href: "#overview", label: "Overview" }, { href: "#chat", label: "AI chat" }, { href: "#content-map", label: "Content map" }, { href: "#accessibility", label: "Accessibility" }, { href: "#settings", label: "Account settings" }, { href: "#health", label: "Health check" }];
const currentRoute = () => window.location.hash.replace("#", "") || "overview";

function Placeholder({ title, description }: { title: string; description: string }) { return <section className="panel" aria-labelledby="page-title"><p className="eyebrow">FlyRank capstone</p><h1 id="page-title">{title}</h1><p className="intro">{description}</p><div className="placeholder-grid" aria-label={`${title} preview`}><div className="placeholder-block" /><div className="placeholder-block short" /><div className="placeholder-block" /></div></section>; }

function HealthPage() { const [health, setHealth] = useState<Health | null>(null); const [error, setError] = useState(false); useEffect(() => { fetch("/health.json").then((response) => { if (!response.ok) throw new Error("health check failed"); return response.json() as Promise<Health>; }).then(setHealth).catch(() => setError(true)); }, []); return <section className="panel" aria-labelledby="page-title"><p className="eyebrow">System status</p><h1 id="page-title">Health check</h1><p className="intro">A fetched-data check confirms the app can render service metadata.</p>{health && <div className="status-card"><span className="status-dot" /><strong>{health.status}</strong><span>{health.service} · updated {health.updatedAt}</span></div>}{error && <p role="alert" className="error">The health endpoint could not be reached.</p>}{!health && !error && <p className="muted">Checking service status…</p>}</section>; }

function ChatPage() {
  const [messages, setMessages] = useState<Message[]>([{ role: "assistant", text: "Hi — I’m the FlyRank assistant. Ask me about your content map, accessibility, or next build step." }]);
  const [draft, setDraft] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const abortRef = useRef<AbortController | null>(null); const streamRef = useRef<HTMLDivElement>(null);
  const send = async (value = draft) => { const text = value.trim(); if (!text || busy) return; const next = [...messages, { role: "user" as const, text }, { role: "assistant" as const, text: "" }]; setMessages(next); setDraft(""); setBusy(true); setError(""); const controller = new AbortController(); abortRef.current = controller; try { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: next.slice(0, -1).map((message) => ({ role: message.role, content: message.text })) }), signal: controller.signal }); if (!response.ok || !response.body) throw new Error("stream unavailable"); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; while (true) { const result = await reader.read(); if (result.done) break; buffer += decoder.decode(result.value, { stream: true }); const lines = buffer.split("\n"); buffer = lines.pop() ?? ""; for (const line of lines) { if (!line.startsWith("data: ")) continue; if (line === "data: [DONE]") continue; const payload = JSON.parse(line.slice(6)) as { text?: string }; if (payload.text) setMessages((current) => current.map((item, index) => index === current.length - 1 ? { ...item, text: item.text + payload.text } : item)); } streamRef.current?.scrollTo({ top: streamRef.current.scrollHeight, behavior: "smooth" }); } } catch (caught) { if ((caught as Error).name !== "AbortError") setError("The stream could not be reached. Try again."); } finally { setBusy(false); abortRef.current = null; } };
  const stop = () => abortRef.current?.abort();
  return <section className="chat-panel" aria-labelledby="chat-title"><div className="chat-heading"><div><p className="eyebrow">AI-assisted workflow</p><h1 id="chat-title">Build with a clear next step</h1><p className="intro">Messages stream from a server-side route; no API key is exposed in the browser.</p></div><span className="online-pill"><span className="status-dot" /> {busy ? "Streaming" : "Ready"}</span></div><div className="suggestions" aria-label="Suggested prompts">{["What should I build next?", "Check my accessibility plan", "Turn this into a small screen"].map((suggestion) => <button key={suggestion} type="button" onClick={() => void send(suggestion)} disabled={busy}>{suggestion}</button>)}</div><div ref={streamRef} className="messages" aria-live="polite" aria-label="Conversation">{messages.map((message, index) => <div key={`${message.role}-${index}`} className={`message ${message.role}`}><span className="message-label">{message.role === "assistant" ? "Assistant" : "You"}</span><p>{message.text || (busy ? "Thinking…" : "No response received.")}</p></div>)}</div>{error && <p className="error" role="alert">{error}</p>}<form className="chat-form" onSubmit={(event) => { event.preventDefault(); void send(); }}><label htmlFor="chat-input">Message</label><div><input id="chat-input" value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Describe the next thing you want to make" /><button type="submit" disabled={busy || !draft.trim()}>Send</button>{busy && <button type="button" className="stop-button" onClick={stop}>Stop</button>}</div></form></section>;
}

export function App() { const [route, setRoute] = useState(currentRoute); useEffect(() => { const onHashChange = () => setRoute(currentRoute()); window.addEventListener("hashchange", onHashChange); return () => window.removeEventListener("hashchange", onHashChange); }, []); const page = route === "health" ? <HealthPage /> : route === "chat" ? <ChatPage /> : route === "settings" ? <Placeholder title="Account settings" description="Settings form workflow drill." /> : route === "content-map" ? <Placeholder title="Content map" description="A clear route for mapping content, calls to action, and the next decision." /> : route === "accessibility" ? <Placeholder title="Accessibility" description="A dedicated space for keyboard, contrast, and responsive checks." /> : <Placeholder title="Capstone workspace" description="A responsive, accessible shell for the FlyRank frontend capstone." />; return <div className="app-shell"><header className="topbar"><a className="brand" href="#overview" aria-label="FlyRank capstone home"><span className="brand-mark">F</span> FlyRank</a><nav aria-label="Primary navigation"><ul>{routes.map((item) => <li key={item.href}><a className={route === item.href.slice(1) ? "active" : ""} href={item.href}>{item.label}</a></li>)}</ul></nav></header><main className="shell">{page}</main><footer className="footer"><span>Frontend AI Engineering · Week 4</span><a href="#health">Service status</a></footer></div>; }
